name: libmfx

inputs:
  refId:
    type: string
    required: true
  config:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - name: Publish artifact
    uses: actions/upload-artifact@v2
    with:
      name: libmfx-${{ runner.os }}-${{ inputs.config }}
      path: .github/actions/libmfx/libmfx.tgz
